import React, { useState } from 'react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onClose: (dontShowAgain: boolean) => void;
}

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, onClose }) => {
  const [dontShowAgain, setDontShowAgain] = useState(false);

  if (!isOpen) return null;

  const handleConfirm = () => {
    onClose(dontShowAgain);
  };

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-70 z-50 flex justify-center items-center backdrop-blur-sm" 
    >
      <div 
        className="bg-slate-800/80 backdrop-blur-xl border border-yellow-500/50 rounded-lg shadow-2xl p-6 w-full max-w-lg m-4 relative text-gray-200"
      >
        <h2 className="text-2xl font-bold mb-4 text-yellow-400 flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            Warning & Disclaimer
        </h2>

        <div className="space-y-4 text-gray-300">
            <p>
                As an AI-powered assistant, Scripture Scholar may occasionally produce inaccurate information, inconsistencies, or "hallucinations." 
            </p>
            <p>
                The responses provided are generated by a large language model and are outside of my direct control. Always verify critical information against the official scriptures and publications of The Church of Jesus Christ of Latter-day Saints.
            </p>
        </div>
        
        <div className="mt-6 flex items-center justify-between">
            <label className="flex items-center space-x-2 text-sm text-gray-400 cursor-pointer">
                <input
                    type="checkbox"
                    checked={dontShowAgain}
                    onChange={(e) => setDontShowAgain(e.target.checked)}
                    className="rounded bg-slate-700 border-slate-500 text-blue-500 focus:ring-blue-500 h-4 w-4"
                />
                <span>Don't show again</span>
            </label>

            <button
                onClick={handleConfirm}
                className="bg-red-600 text-white py-2 px-6 rounded-md hover:bg-red-700 transition-colors font-semibold"
            >
                Okay
            </button>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerModal;